config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "stories#index"

  resources :stories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/story.rb
class Story < ApplicationRecord
  validates :title, presence: true, length: { in: 1..100 }
  validates :body, presence: true, length: { in: 1..40000 }

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :stories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

private
  
  def sign_up_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
  end

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @stories = Story.all
  end

  def show
    @story = Story.find(params[:id])
    @stories = Story.all
  end

  def new
    @story = current_user.stories.build
  end

  def create
    @story = current_user.stories.build(story_params)

    if @story.save
      redirect_to root_path
    else
      render :new
    end
  end

  private
    def story_params
      params.require(:story).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Writers Only</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-primary global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notification is-danger global-notification">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>
    <nav class="navbar is-dark">
      <div class="navbar-brand">
      <%= link_to root_path, class: "navbar-item" do %>
          <h1 class="title is-4">Writers Only</h1>
      <% end %>
          <div class="navbar-burger burger" data-target="navbarExample">
            <span></span>
            <span></span>
            <span></span>
          </div>
      </div>

      <div id="navbarExample" class="navbar-menu">
        <div class="navbar-start">
          <div class="navbar-item">
          <div class="field is-grouped">
            <p class="control">
              <%= link_to 'New Story', new_story_path, class: "button is-warning is-rounded" %>
            </p>
            </div>
          </div>
        </div>
        <div class="navbar-end">
          <div class="navbar-item">
          <div class="field is-grouped">
            <% if user_signed_in? %>
              <p class="control">
                <%= link_to current_user.name, edit_user_registration_path, class: "button is-link is-rounded" %>
              </p>
              <p>
                <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "button is-link is-rounded" %>
              </p>
            <% else %>
             <p class="control">
              <%= link_to 'Sign In', new_user_session_path, class: "button is-link is-rounded" %>
            </p>
            <p class="control">
              <%= link_to 'Sign Up', new_user_registration_path, class: "button is-link is-rounded" %>
            </p>
            <% end %>
            </div>
          </div>
        </div>
      </div>

    </nav>
    <%= yield %>
  </body>
</html>

app/views/stories/_author_profile.html.erb
<div class="panel">
  <p class="panel-heading has-text-centered has-background-dark has-text-white">Author</p>
  <div class="panel-block has-background-warning">
    <div class="media-left">
      <figure class=" image is 64-64">
        <%= gravatar_image_tag(@story.user.email, size: 64, alt: @story.user.name) %>
      </figure>
    </div>
    <p class="panel-heading has-text-left has-background-warning is-6">
      <%= @story.user.name %><br />
      <i><small><%= @story.user.username %></small></i>
    </p>
  </div>
</div>
<div class="panel">
  <p class="panel-heading has-text-centered has-background-dark has-text-white">Author's Stories</p>
    <div class="panel-block has-background-warning">
      <ul>
        <% author_id = @story.user.id %>
        <% @stories.order(created_at: :desc).each do |story| %>
          <% if story.user.id == author_id %>
            <li class="is-size-7"><%= link_to story.title, story %></li>
          <% end %> 
        <% end %>
      </ul>
    </div>
</div>
    

app/views/stories/_form.html.erb
<%= simple_form_for(@story) do |f| %>
<%= f.error_notification %>
<div class="field">
  <div class="control">
    <%= f.input :title, label: "Title", input_html: { class: "input" }, wrapper: false, label_html: {class: "label"}, 
    placeholder: "Make it a good one...", autofocus: true %>
  </div>
  <div class="control">
    <%= f.input :body, label: "Body", input_html: { class: "textarea" }, wrapper: false, label_html: {class: "label"}, 
    placeholder: "Just start writing..." %>
  </div>
</div>
<%= f.button :submit, class: "button is-link is-rounded is-medium" %>
<% end %>

app/views/stories/_latest_stories.html.erb
<div class="panel">
  <p class="panel-heading has-text-centered has-background-dark has-text-white">Latest Stories</p>
    <div class="panel-block has-background-warning">
      <ul>
        <% @stories.order(created_at: :desc).limit(4).each do |story| %>
          <li class="is-size-7"><%= link_to story.title, story %></li>
        <% end %>
      </ul>
    </div>
</div>

app/views/stories/_most_stories.html.erb
<div class="panel">
  <p class="panel-heading has-text-centered has-background-dark has-text-white">Most Stories</p>
    <div class="panel-block has-background-warning">
      <ul>
        <% @user = User.all %>
        <% @user = @user.sort_by { |user| user.stories.count } %>
        <% @user.reverse_each do |user| %>
          <li class="is-size-6">
            <%= user.stories.count %>
            <% if user_signed_in? %>    
              <%= user.username %>
            <% else %>
              <i>Log in to see username</i>
            <% end %>
          </li>
        <% end %>   
      </ul>
    </div>
</div>

app/views/stories/_stories_feed.html.erb
<h2 class="has-text-centered title is-3">Stories</h2>
  <% @stories.each do |story| %>
    <p class="subtitle is-5">
      <%= link_to story.title, story %>
    </p>
    <p>
      <%= simple_format story.body.gsub("\n", " ") %>
    </p><br/>
    <p class="is-italic">Written by:</p>
      <% if user_signed_in? %>
        <%= story.user.name %>
        <div class="is-italic">
          <%= story.user.username %>
        </div><br/>
      <% else %>
        <p class="has-text-weight-bold is-uppercase">Log in to see author</p><br/>
      <% end %> 
  <% end %>
  

app/views/stories/_user_profile.html.erb
<div class="panel">
    <p class="panel-heading has-text-centered has-background-dark has-text-white">Writer Profile</p>
    <div class="panel-block has-background-warning">
      <article class="media">
        <div class="media-left">
          <figure class=" image is 64-64">
            <%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name) %>
          </figure>
        </div>
        <div class="media-content">
          <div class="content">
            <p>
              <strong><%= current_user.name %></strong><br />
              <small><%= current_user.username %></small>
            </p>
          </div>
        </div>
      </article>
    </div>
    <div class="panel-block">
      <div class="level is-mobile">
        <div class="level-item has-centered-text">
          <div>
            <p class="heading">Stories</p>
            <p class="title is-6"><%= current_user.stories.count %></p>
          </div>
        </div>
    </div>
  </div>
</div>

app/views/stories/index.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-variable is-6-desktop">
      <div class="column is-one-quarter">
        <% if user_signed_in? %>
          <%= render 'user_profile' %>
        <% else %>
        <div class="panel">
          <p class="panel-heading has-text-centered has-background-dark has-text-white">Writer Profile</p>
          <div class="panel-block has-background-warning">
            <p class="panel-heading has-text-centered has-background-warning title is-6">Log in to see profile</p>
          </div>
        </div>
        <% end %>
        <%= render 'latest_stories' %>
        <%= render 'most_stories' %>
      </div>
      <div class="column is-three-quarters has-background-white-ter">
        <%= render 'stories_feed' %>
      </div>
    </div>
  </div>
</section>

app/views/stories/new.html.erb
<div class="section">
  <div class="container">
    <div class="columns is-centered is-variable is-6-desktop">
      <div class="column is-one-quarter">
        <% if user_signed_in? %>
          <%= render 'user_profile' %>
        <% else %>
          <div class="panel">
            <p class="panel-heading has-text-centered has-background-dark has-text-white">Writer Profile</p>
            <div class="panel-block has-background-warning">
            <p class="panel-heading has-text-centered has-background-warning title is-6">Log in to see profile</p>
            </div>
          </div>
        <% end %>
      </div>
      <div class="column is-three-quarters">
        <h1 class="title">Share a Story</h1>
          <%= render 'form' %>
      </div>
    </div>
  </div>
</div>
<nav class="navbar is-fixed-bottom">
  <div class="navbar-menu">
    <div class="navbar-item">
      <div class="field is-grouped">
        <p class="control">
          <%= link_to 'Reset', new_story_path, class: "button is-dark" %>
        </p>
      </div>
    </div>
  </div>
</nav>

app/views/stories/show.html.erb
<div class="section">
  <div class="container">
    <div class="columns is-centered is-variable is-6-desktop">
      <div class="column is-one-quarter">
        <% if user_signed_in? %>
          <%= render 'author_profile' %>
        <% else %>
          <div class="panel">
            <p class="panel-heading has-text-centered has-background-dark has-text-white">Author</p>
            <div class="panel-block has-background-warning">
             <p class="panel-heading has-text-left has-background-warning title is-6">Log in to see author</p>
            </div>
          </div>
          <div class="panel">
            <p class="panel-heading has-text-centered has-background-dark has-text-white">Other Stories</p>
            <div class="panel-block has-background-warning">
             <p class="panel-heading has-text-left has-background-warning title is-6">Log in for author's other stories</p>
            </div>
          </div>
        <% end %>
        <%= render 'latest_stories' %>
        <%= render 'most_stories' %>
      </div>   
      <div class="column is-three-quarters has-background-white-ter">
        <h1 class="title has-text-centered">
          <%= @story.title %>
        </h1>
        <p>
          <%= simple_format @story.body.gsub("\n", " ") %>
        </p> 
      </div>
    </div>
  </div>
</div>